"""Callbacks that make decisions depending how a monitored metric/loss behaves"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/17_callback.tracker.ipynb.

# %% ../../nbs/17_callback.tracker.ipynb 2
from __future__ import annotations
import copy
from ..basics import *
from .progress import *

# %% auto 0
__all__ = ['TerminateOnNaNCallback', 'TrackerCallback', 'EarlyStoppingCallback', 'MultiMetricEarlyStoppingCallback', 'SaveModelCallback',
           'ReduceLROnPlateau', 'CheckpointAveragingCallback', 'StochasticWeightAveraging']

# %% ../../nbs/17_callback.tracker.ipynb 6
class TerminateOnNaNCallback(Callback):
    "A `Callback` that terminates training if loss is NaN."
    order=-9
    def after_batch(self):
        "Test if `last_loss` is NaN and interrupts training."
        if torch.isinf(self.loss) or torch.isnan(self.loss): raise CancelFitException

# %% ../../nbs/17_callback.tracker.ipynb 10
class TrackerCallback(Callback):
    "A `Callback` that keeps track of the best value in `monitor`."
    order,remove_on_fetch,_only_train_loop = 60,True,True
    def __init__(self, 
        monitor='valid_loss', # value (usually loss or metric) being monitored.
        comp=None, # numpy comparison operator; np.less if monitor is loss, np.greater if monitor is metric.
        min_delta=0., # minimum delta between the last monitor value and the best monitor value.
        reset_on_fit=True # before model fitting, reset value being monitored to -infinity (if monitor is metric) or +infinity (if monitor is loss).
    ):
        if comp is None: comp = np.less if 'loss' in monitor or 'error' in monitor else np.greater
        if comp == np.less: min_delta *= -1
        self.monitor,self.comp,self.min_delta,self.reset_on_fit,self.best= monitor,comp,min_delta,reset_on_fit,None

    def before_fit(self):
        "Prepare the monitored value"
        self.run = not hasattr(self, "lr_finder") and not hasattr(self, "gather_preds")
        if self.reset_on_fit or self.best is None: self.best = float('inf') if self.comp == np.less else -float('inf')
        assert self.monitor in self.recorder.metric_names[1:]
        self.idx = list(self.recorder.metric_names[1:]).index(self.monitor)

    def after_epoch(self):
        "Compare the last value to the best up to now"
        val = self.recorder.values[-1][self.idx]
        if self.comp(val - self.min_delta, self.best): self.best,self.new_best = val,True
        else: self.new_best = False

    def after_fit(self): self.run=True

# %% ../../nbs/17_callback.tracker.ipynb 19
class EarlyStoppingCallback(TrackerCallback):
    "A `TrackerCallback` that terminates training when monitored quantity stops improving."
    order=TrackerCallback.order+3
    def __init__(self, 
        monitor='valid_loss', # value (usually loss or metric) being monitored.
        comp=None, # numpy comparison operator; np.less if monitor is loss, np.greater if monitor is metric.
        min_delta=0., # minimum delta between the last monitor value and the best monitor value.
        patience=1, # number of epochs to wait when training has not improved model.
        reset_on_fit=True # before model fitting, reset value being monitored to -infinity (if monitor is metric) or +infinity (if monitor is loss).
    ):
        super().__init__(monitor=monitor, comp=comp, min_delta=min_delta, reset_on_fit=reset_on_fit)
        self.patience = patience

    def before_fit(self): self.wait = 0; super().before_fit()
    def after_epoch(self):
        "Compare the value monitored to its best score and maybe stop training."
        super().after_epoch()
        if self.new_best: self.wait = 0
        else:
            self.wait += 1
            if self.wait >= self.patience:
                print(f'No improvement since epoch {self.epoch-self.wait}: early stopping')
                raise CancelFitException()

# %% ../../nbs/17_callback.tracker.ipynb 23
class MultiMetricEarlyStoppingCallback(Callback):
    "A `Callback` that terminates training when multiple monitored metrics stop improving."
    order = TrackerCallback.order+3
    def __init__(self,
        monitors=('valid_loss',), # list of values (losses or metrics) to monitor.
        comp=None, # list of numpy comparison operators, one per monitor; defaults based on monitor name.
        min_delta=0., # minimum delta for improvement; scalar applied to all, or list per monitor.
        patience=1, # number of epochs to wait when training has not improved.
        logic='all', # 'all' means stop only when ALL metrics stagnate; 'any' means stop when ANY metric stagnates.
        reset_on_fit=True # before model fitting, reset monitored values.
    ):
        assert logic in ('all', 'any'), "logic must be 'all' or 'any'"
        self.monitors = list(monitors)
        n = len(self.monitors)
        # Set up comparators
        if comp is None:
            self.comps = [np.less if ('loss' in m or 'error' in m) else np.greater for m in self.monitors]
        else:
            self.comps = list(comp) if hasattr(comp, '__iter__') else [comp] * n
        # Set up min_delta per monitor
        if isinstance(min_delta, (list, tuple)):
            self.min_deltas = list(min_delta)
        else:
            self.min_deltas = [min_delta * (-1 if c == np.less else 1) for c in self.comps]
        # Adjust sign for scalar case
        if not isinstance(min_delta, (list, tuple)):
            pass  # already handled above
        else:
            self.min_deltas = [d * (-1 if c == np.less else 1) for d, c in zip(self.min_deltas, self.comps)]
        self.patience = patience
        self.logic = logic
        self.reset_on_fit = reset_on_fit

    def before_fit(self):
        "Prepare monitored values"
        self.run = not hasattr(self, "lr_finder") and not hasattr(self, "gather_preds")
        n = len(self.monitors)
        if self.reset_on_fit or not hasattr(self, 'bests'):
            self.bests = [float('inf') if c == np.less else -float('inf') for c in self.comps]
        self.waits = [0] * n
        # Validate all monitors exist
        for m in self.monitors:
            assert m in self.recorder.metric_names[1:], f"Monitor '{m}' not found in metrics"
        self.idxs = [list(self.recorder.metric_names[1:]).index(m) for m in self.monitors]

    def after_epoch(self):
        "Compare each monitored value to its best and maybe stop training."
        stagnant = []
        for i, (idx, comp, min_delta, best) in enumerate(
            zip(self.idxs, self.comps, self.min_deltas, self.bests)
        ):
            val = self.recorder.values[-1][idx]
            if comp(val - min_delta, best):
                self.bests[i] = val
                self.waits[i] = 0
                stagnant.append(False)
            else:
                self.waits[i] += 1
                stagnant.append(self.waits[i] >= self.patience)

        should_stop = all(stagnant) if self.logic == 'all' else any(stagnant)
        if should_stop:
            print(f'No improvement since epoch {self.epoch-max(self.waits)}: early stopping (logic={self.logic})')
            raise CancelFitException()

    def after_fit(self): self.run = True

# %% ../../nbs/17_callback.tracker.ipynb 26
class SaveModelCallback(TrackerCallback):
    "A `TrackerCallback` that saves the model's best during training and loads it at the end."
    order = TrackerCallback.order+1
    def __init__(self, 
        monitor='valid_loss', # value (usually loss or metric) being monitored.
        comp=None, # numpy comparison operator; np.less if monitor is loss, np.greater if monitor is metric.
        min_delta=0., # minimum delta between the last monitor value and the best monitor value.
        fname='model', # model name to be used when saving model.
        every_epoch=False, # if true, save model after every epoch; else save only when model is better than existing best.
        at_end=False, # if true, save model when training ends; else load best model if there is only one saved model.
        with_opt=False, # if true, save optimizer state (if any available) when saving model. 
        reset_on_fit=True # before model fitting, reset value being monitored to -infinity (if monitor is metric) or +infinity (if monitor is loss).
    ):
        super().__init__(monitor=monitor, comp=comp, min_delta=min_delta, reset_on_fit=reset_on_fit)
        assert not (every_epoch and at_end), "every_epoch and at_end cannot both be set to True"
        # keep track of file path for loggers
        self.last_saved_path = None
        store_attr('fname,every_epoch,at_end,with_opt')

    def _save(self, name): self.last_saved_path = self.learn.save(name, with_opt=self.with_opt)

    def after_epoch(self):
        "Compare the value monitored to its best score and save if best."
        if self.every_epoch:
            if (self.epoch%self.every_epoch) == 0: self._save(f'{self.fname}_{self.epoch}')
        else: #every improvement
            super().after_epoch()
            if self.new_best:
                print(f'Better model found at epoch {self.epoch} with {self.monitor} value: {self.best}.')
                self._save(f'{self.fname}')

    def after_fit(self, **kwargs):
        "Load the best model."
        if self.at_end: self._save(f'{self.fname}')
        elif not self.every_epoch: self.learn.load(f'{self.fname}', with_opt=self.with_opt)

# %% ../../nbs/17_callback.tracker.ipynb 30
class ReduceLROnPlateau(TrackerCallback):
    "A `TrackerCallback` that reduces learning rate when a metric has stopped improving."
    order=TrackerCallback.order+2
    def __init__(self, 
        monitor='valid_loss', # value (usually loss or metric) being monitored.
        comp=None, # numpy comparison operator; np.less if monitor is loss, np.greater if monitor is metric.
        min_delta=0., # minimum delta between the last monitor value and the best monitor value.
        patience=1, # number of epochs to wait when training has not improved model.
        factor=10., # the denominator to divide the learning rate by, when reducing the learning rate.
        min_lr=0, # the minimum learning rate allowed; learning rate cannot be reduced below this minimum.
        reset_on_fit=True # before model fitting, reset value being monitored to -infinity (if monitor is metric) or +infinity (if monitor is loss).
    ):
        super().__init__(monitor=monitor, comp=comp, min_delta=min_delta, reset_on_fit=reset_on_fit)
        self.patience,self.factor,self.min_lr = patience,factor,min_lr

    def before_fit(self): self.wait = 0; super().before_fit()
    def after_epoch(self):
        "Compare the value monitored to its best score and reduce LR by `factor` if no improvement."
        super().after_epoch()
        if self.new_best: self.wait = 0
        else:
            self.wait += 1
            if self.wait >= self.patience:
                old_lr = self.opt.hypers[-1]['lr']
                for h in self.opt.hypers: h['lr'] = max(h['lr'] / self.factor, self.min_lr)
                self.wait = 0
                if self.opt.hypers[-1]["lr"] < old_lr:
                    print(f'Epoch {self.epoch}: reducing lr to {self.opt.hypers[-1]["lr"]}')

# %%
class CheckpointAveragingCallback(TrackerCallback):
    """A `TrackerCallback` that maintains top-K model checkpoints and averages their weights at the end of training.

    Note: Each stored checkpoint is a full deep-copy of the model state_dict. For large models,
    this can consume significant memory (e.g., ~100 MB per slot for ResNet-50, ~1.2 GB for ViT-Large).
    Choose `k` accordingly based on available memory.
    """
    order = TrackerCallback.order+2
    def __init__(self,
        monitor='valid_loss', # value (usually loss or metric) being monitored.
        comp=None, # numpy comparison operator; np.less if monitor is loss, np.greater if monitor is metric.
        min_delta=0., # minimum delta between the last monitor value and the best monitor value.
        k=5, # number of top checkpoints to keep for averaging.
        save_averaged=False, # if True, save the averaged model to disk at end of training.
        fname='averaged_model', # filename used when saving the averaged model.
        reset_on_fit=True # before model fitting, reset value being monitored to -infinity (if monitor is metric) or +infinity (if monitor is loss).
    ):
        super().__init__(monitor=monitor, comp=comp, min_delta=min_delta, reset_on_fit=reset_on_fit)
        self.k,self.save_averaged,self.fname = k,save_averaged,fname

    def before_fit(self):
        "Initialize the top-K checkpoint list."
        super().before_fit()
        self.top_k = []
        if self.run:
            print(f'CheckpointAveragingCallback: will keep up to {self.k} checkpoint copies in memory.')

    def after_epoch(self):
        "Store a copy of the model state_dict if it is among the top-K."
        if not self.run: return
        super().after_epoch()
        val = self.recorder.values[-1][self.idx]
        state = copy.deepcopy(self.model.state_dict())
        if len(self.top_k) < self.k:
            self.top_k.append((val, state))
            self.top_k.sort(key=lambda x: x[0], reverse=(self.comp == np.greater))
        elif self.comp(val, self.top_k[-1][0]):
            self.top_k[-1] = (val, state)
            self.top_k.sort(key=lambda x: x[0], reverse=(self.comp == np.greater))

    def _is_floating_point(self, tensor):
        "Check if a tensor is floating-point (works for both PyTorch tensors and numpy arrays)."
        if hasattr(tensor, 'is_floating_point'):
            return tensor.is_floating_point()
        # For numpy arrays, check dtype kind
        if hasattr(tensor, 'dtype'):
            return tensor.dtype.kind == 'f'
        return True  # default to treating as float

    def after_fit(self):
        "Average the stored state_dicts and load into the model."
        if len(self.top_k) > 0:
            avg_state = {}
            keys = self.top_k[0][1].keys()
            # Use the best checkpoint (first in sorted list) for non-float buffers
            best_state = self.top_k[0][1]
            for key in keys:
                tensors = [sd[key] for _, sd in self.top_k]
                if self._is_floating_point(tensors[0]):
                    avg_state[key] = sum(tensors) / len(tensors)
                else:
                    # For integer buffers (e.g. num_batches_tracked), use the best checkpoint's value
                    avg_state[key] = copy.deepcopy(best_state[key])
            self.model.load_state_dict(avg_state)
            if self.save_averaged:
                self.learn.save(self.fname)
        super().after_fit()

# %%
class StochasticWeightAveraging(Callback):
    """A `Callback` that maintains an exponential moving average (EMA) of model weights.

    During training, the EMA shadow weights are updated after each training batch.
    Before validation, the current training weights are saved and the EMA weights are
    loaded into the model. After validation, the training weights are restored so
    training continues with the original (non-averaged) parameters.

    At the end of training, the EMA weights are loaded as the final model weights
    for improved generalization.
    """
    order = 65  # After TrackerCallback (60) but flexible ordering

    def __init__(self,
        decay=0.999, # EMA decay factor; higher values produce smoother averages.
        start_epoch=0, # epoch index at which EMA accumulation begins (0 = from the start).
        load_ema_at_end=True # if True, load EMA weights as the final model weights after training.
    ):
        self.decay = decay
        self.start_epoch = start_epoch
        self.load_ema_at_end = load_ema_at_end

    def before_fit(self):
        "Initialize EMA shadow weights as a copy of the current model parameters."
        self.run = not hasattr(self, "lr_finder") and not hasattr(self, "gather_preds")
        if not self.run: return
        self.ema_state = copy.deepcopy(self.model.state_dict())
        self._training_state = None

    def after_batch(self):
        "Update EMA shadow weights after each training batch."
        if not self.run or not self.training: return
        if self.epoch < self.start_epoch: return
        decay = self.decay
        current_state = self.model.state_dict()
        for key in self.ema_state:
            if self._is_floating_point(self.ema_state[key]):
                self.ema_state[key] = decay * self.ema_state[key] + (1.0 - decay) * current_state[key]

    def before_validate(self):
        "Swap in EMA weights before validation."
        if not self.run: return
        self._training_state = copy.deepcopy(self.model.state_dict())
        self.model.load_state_dict(self.ema_state)

    def after_validate(self):
        "Restore training weights after validation."
        if not self.run or self._training_state is None: return
        self.model.load_state_dict(self._training_state)
        self._training_state = None

    def after_fit(self):
        "Optionally load EMA weights as the final model weights."
        if not self.run: return
        if self.load_ema_at_end:
            self.model.load_state_dict(self.ema_state)

    def _is_floating_point(self, tensor):
        "Check if a tensor is floating-point."
        if hasattr(tensor, 'is_floating_point'):
            return tensor.is_floating_point()
        if hasattr(tensor, 'dtype'):
            return tensor.dtype.kind == 'f'
        return True
