"""Various callbacks to customize training behavior"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/18a_callback.training.ipynb.

# %% ../../nbs/18a_callback.training.ipynb 2
from __future__ import annotations
from ..basics import *
from .progress import *
from .fp16 import *

# %% auto 0
__all__ = ['bn_types', 'ShortEpochCallback', 'GradientAccumulation', 'GradientClip', 'set_bn_eval', 'BnFreeze',
           'StochasticWeightAveraging']

# %% ../../nbs/18a_callback.training.ipynb 6
class ShortEpochCallback(Callback):
    "Fit just `pct` of an epoch, then stop"
    def __init__(self,pct=0.01,short_valid=True): self.pct,self.short_valid = pct,short_valid
    def after_batch(self):
        if self.iter/self.n_iter < self.pct: return
        if self.training:    raise CancelTrainException
        if self.short_valid: raise CancelValidException

# %% ../../nbs/18a_callback.training.ipynb 10
class GradientAccumulation(Callback):
    "Accumulate gradients before updating weights"
    order,run_valid = MixedPrecision.order-4,False
    def __init__(self, n_acc=32): store_attr()
    def before_fit(self): self.count=0
    def after_loss(self): self.learn.loss_grad /= self.n_acc/find_bs(self.learn.yb)
    def before_step(self):
        "Skip weight update if we have not seen enough items"
        self.learn.loss_grad *= self.n_acc/find_bs(self.learn.yb) # log correct loss
        self.count += find_bs(self.learn.yb)
        if self.count<self.n_acc: raise CancelBatchException() # skip step/zero_grad
        else: self.count=0

# %% ../../nbs/18a_callback.training.ipynb 16
class GradientClip(Callback):
    "Clip norm of gradients"
    order=MixedPrecision.order+1
    def __init__(self,max_norm:float=1., norm_type:float=2.0): store_attr()
    def before_step(self): nn.utils.clip_grad_norm_(self.parameters(), self.max_norm, self.norm_type)

# %% ../../nbs/18a_callback.training.ipynb 23
bn_types = (nn.BatchNorm1d, nn.BatchNorm2d, nn.BatchNorm3d)

def set_bn_eval(m:nn.Module, use_eval=True)->None:
    "Set bn layers in eval mode for all recursive children of `m`."
    for l in m.children():
        if isinstance(l, bn_types) and not next(l.parameters()).requires_grad:
            if use_eval: l.eval()
            else:        l.train()
        set_bn_eval(l)

class BnFreeze(Callback):
    run_after=TrainEvalCallback
    "Freeze moving average statistics in all non-trainable batchnorm layers."
    def before_train(self):
        set_bn_eval(self.model)

# %% ../../nbs/18a_callback.training.ipynb 35
class StochasticWeightAveraging(Callback):
    "Maintains an exponential moving average of model weights and swaps to averaged weights at evaluation time"
    order,run_valid = MixedPrecision.order+2,True
    def __init__(self, decay:float=0.999, start_epoch:int=1):
        "Create SWA callback with EMA `decay` factor, starting after `start_epoch` epochs"
        store_attr()
    def before_fit(self):
        "Initialize EMA parameters as a copy of the model parameters"
        self.ema_params = [p.clone().detach() for p in self.parameters()]
        self.epoch_count = 0
    def after_step(self):
        "Update EMA parameters with exponential moving average after each optimizer step"
        if self.epoch_count < self.start_epoch: return
        with torch.no_grad():
            for ema_p, model_p in zip(self.ema_params, self.parameters()):
                ema_p.mul_(self.decay).add_(model_p.data, alpha=1-self.decay)
    def before_epoch(self):
        "Track epoch count"
        self.epoch_count = self.epoch
    def before_validate(self):
        "Swap model weights with EMA weights before validation"
        if self.epoch_count < self.start_epoch: return
        self._stored_params = [p.data.clone() for p in self.parameters()]
        for model_p, ema_p in zip(self.parameters(), self.ema_params):
            model_p.data.copy_(ema_p)
    def after_validate(self):
        "Restore original model weights after validation"
        if not hasattr(self, '_stored_params') or self._stored_params is None: return
        for model_p, stored_p in zip(self.parameters(), self._stored_params):
            model_p.data.copy_(stored_p)
        self._stored_params = None
    def after_fit(self):
        "Swap to EMA weights permanently after training completes"
        if self.epoch_count >= self.start_epoch:
            for model_p, ema_p in zip(self.parameters(), self.ema_params):
                model_p.data.copy_(ema_p)
        if hasattr(self, 'ema_params'): del self.ema_params
        if hasattr(self, '_stored_params'): del self._stored_params
