"""Helper functions to download the fastai datasets"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_data.external.ipynb.

# %% ../../nbs/04_data.external.ipynb 2
from __future__ import annotations
from ..torch_basics import *
from fastdownload import FastDownload
from functools import lru_cache
import fastai.data

# %% auto 0
__all__ = ['fastai_cfg', 'fastai_path', 'URLs', 'untar_data', 'fastai_lineage_path', 'dataset_hash', 'DatasetSnapshot',
           'register_snapshot', 'list_snapshots', 'get_snapshot', 'reproduce_snapshot']

# %% ../../nbs/04_data.external.ipynb 24
@lru_cache(maxsize=None)
def fastai_cfg() -> Config: # Config that contains default download paths for `data`, `model`, `storage` and `archive`
    "`Config` object for fastai's `config.ini`"
    return Config(Path(os.getenv('FASTAI_HOME', '~/.fastai')), 'config.ini', create=dict(
        data = 'data', archive = 'archive', storage = 'tmp', model = 'models'))

# %% ../../nbs/04_data.external.ipynb 27
def fastai_path(folder:str) -> Path: 
    "Local path to `folder` in `Config`"
    return fastai_cfg().path(folder)

# %% ../../nbs/04_data.external.ipynb 30
class URLs():
    "Global constants for dataset and model URLs."
    LOCAL_PATH = Path.cwd()
    MDL = 'http://files.fast.ai/models/'
    GOOGLE = 'https://storage.googleapis.com/'
    S3  = 'https://s3.amazonaws.com/fast-ai-'
    URL = f'{S3}sample/'

    S3_IMAGE    = f'{S3}imageclas/'
    S3_IMAGELOC = f'{S3}imagelocal/'
    S3_AUDI     = f'{S3}audio/'
    S3_NLP      = f'{S3}nlp/'
    S3_COCO     = f'{S3}coco/'
    S3_MODEL    = f'{S3}modelzoo/'

    # main datasets
    ADULT_SAMPLE        = f'{URL}adult_sample.tgz'
    BIWI_SAMPLE         = f'{URL}biwi_sample.tgz'
    CIFAR               = f'{URL}cifar10.tgz'
    COCO_SAMPLE         = f'{S3_COCO}coco_sample.tgz'
    COCO_TINY           = f'{S3_COCO}coco_tiny.tgz'
    HUMAN_NUMBERS       = f'{URL}human_numbers.tgz'
    IMDB                = f'{S3_NLP}imdb.tgz'
    IMDB_SAMPLE         = f'{URL}imdb_sample.tgz'
    ML_SAMPLE           = f'{URL}movie_lens_sample.tgz'
    ML_100k             = 'https://files.grouplens.org/datasets/movielens/ml-100k.zip'
    MNIST_SAMPLE        = f'{URL}mnist_sample.tgz'
    MNIST_TINY          = f'{URL}mnist_tiny.tgz'
    MNIST_VAR_SIZE_TINY = f'{S3_IMAGE}mnist_var_size_tiny.tgz'
    PLANET_SAMPLE       = f'{URL}planet_sample.tgz'
    PLANET_TINY         = f'{URL}planet_tiny.tgz'
    IMAGENETTE          = f'{S3_IMAGE}imagenette2.tgz'
    IMAGENETTE_160      = f'{S3_IMAGE}imagenette2-160.tgz'
    IMAGENETTE_320      = f'{S3_IMAGE}imagenette2-320.tgz'
    IMAGEWOOF           = f'{S3_IMAGE}imagewoof2.tgz'
    IMAGEWOOF_160       = f'{S3_IMAGE}imagewoof2-160.tgz'
    IMAGEWOOF_320       = f'{S3_IMAGE}imagewoof2-320.tgz'
    IMAGEWANG           = f'{S3_IMAGE}imagewang.tgz'
    IMAGEWANG_160       = f'{S3_IMAGE}imagewang-160.tgz'
    IMAGEWANG_320       = f'{S3_IMAGE}imagewang-320.tgz'

    # kaggle competitions download dogs-vs-cats -p {DOGS.absolute()}
    DOGS = f'{URL}dogscats.tgz'

    # image classification datasets
    CALTECH_101  = f'{S3_IMAGE}caltech_101.tgz'
    CARS         = f'{S3_IMAGE}stanford-cars.tgz'
    CIFAR_100    = f'{S3_IMAGE}cifar100.tgz'
    CUB_200_2011 = f'{S3_IMAGE}CUB_200_2011.tgz'
    FLOWERS      = f'{S3_IMAGE}oxford-102-flowers.tgz'
    FOOD         = f'{S3_IMAGE}food-101.tgz'
    MNIST        = f'{S3_IMAGE}mnist_png.tgz'
    PETS         = f'{S3_IMAGE}oxford-iiit-pet.tgz'

    # NLP datasets
    AG_NEWS                 = f'{S3_NLP}ag_news_csv.tgz'
    AMAZON_REVIEWS          = f'{S3_NLP}amazon_review_full_csv.tgz'
    AMAZON_REVIEWS_POLARITY = f'{S3_NLP}amazon_review_polarity_csv.tgz'
    DBPEDIA                 = f'{S3_NLP}dbpedia_csv.tgz'
    MT_ENG_FRA              = f'{S3_NLP}giga-fren.tgz'
    SOGOU_NEWS              = f'{S3_NLP}sogou_news_csv.tgz'
    WIKITEXT                = f'{S3_NLP}wikitext-103.tgz'
    WIKITEXT_TINY           = f'{S3_NLP}wikitext-2.tgz'
    YAHOO_ANSWERS           = f'{S3_NLP}yahoo_answers_csv.tgz'
    YELP_REVIEWS            = f'{S3_NLP}yelp_review_full_csv.tgz'
    YELP_REVIEWS_POLARITY   = f'{S3_NLP}yelp_review_polarity_csv.tgz'

    # Image localization datasets
    BIWI_HEAD_POSE     = f"{S3_IMAGELOC}biwi_head_pose.tgz"
    CAMVID             = f'{S3_IMAGELOC}camvid.tgz'
    CAMVID_TINY        = f'{URL}camvid_tiny.tgz'
    LSUN_BEDROOMS      = f'{S3_IMAGE}bedroom.tgz'
    PASCAL_2007        = f'{S3_IMAGELOC}pascal_2007.tgz'
    PASCAL_2012        = f'{S3_IMAGELOC}pascal_2012.tgz'

    # Audio classification datasets
    MACAQUES           = f'{GOOGLE}ml-animal-sounds-datasets/macaques.zip'
    ZEBRA_FINCH        = f'{GOOGLE}ml-animal-sounds-datasets/zebra_finch.zip'

    # Medical Imaging datasets
    #SKIN_LESION        = f'{S3_IMAGELOC}skin_lesion.tgz'
    SIIM_SMALL         = f'{S3_IMAGELOC}siim_small.tgz'
    TCGA_SMALL         = f'{S3_IMAGELOC}tcga_small.tgz'

    #Pretrained models
    OPENAI_TRANSFORMER = f'{S3_MODEL}transformer.tgz'
    WT103_FWD          = f'{S3_MODEL}wt103-fwd.tgz'
    WT103_BWD          = f'{S3_MODEL}wt103-bwd.tgz'

    def path(
        url:str='.', # File to download
        c_key:str='archive' # Key in `Config` where to save URL
    ) -> Path:
        "Local path where to download based on `c_key`"
        fname = url.split('/')[-1]
        local_path = URLs.LOCAL_PATH/('models' if c_key=='model' else 'data')/fname
        if local_path.exists(): return local_path
        return fastai_path(c_key)/fname

# %% ../../nbs/04_data.external.ipynb 35
def untar_data(
    url:str, # File to download
    archive:Path=None, # Optional override for `Config`'s `archive` key
    data:Path=None, # Optional override for `Config`'s `data` key
    c_key:str='data', # Key in `Config` where to extract file
    force_download:bool=False, # Setting to `True` will overwrite any existing copy of data
    track_lineage:bool=False, # Record a dataset snapshot (url, path, content hash, timestamp) in the lineage registry for reproducibility
    base:str='~/.fastai' # Directory containing config file and base of relative paths
) -> Path: # Path to extracted file(s)
    "Download `url` using `FastDownload.get`"
    d = FastDownload(fastai_cfg(), module=fastai.data, archive=archive, data=data, base=base)
    res = d.get(url, force=force_download, extract_key=c_key)
    if track_lineage: register_snapshot(url, res)
    return res

# %% ../../nbs/04_data.external.ipynb 39
import hashlib, json
from datetime import datetime, timezone

# %% ../../nbs/04_data.external.ipynb 40
def fastai_lineage_path() -> Path: # Path to the dataset lineage registry JSON file
    "Path to the dataset lineage registry JSON file"
    return fastai_cfg().path('storage')/'lineage.json'

# %% ../../nbs/04_data.external.ipynb 41
def dataset_hash(
    path:Path, # Extracted dataset directory or file to hash
    chunk_size:int=1<<20 # Bytes read per chunk to bound memory use
) -> str: # SHA-256 hex digest over file contents and relative names
    "Deterministic SHA-256 digest of the data at `path` (stable across runs)"
    path = Path(path)
    h = hashlib.sha256()
    if path.is_dir():
        files = sorted((f for f in path.rglob('*') if f.is_file()), key=lambda f: f.relative_to(path).as_posix())
        for f in files:
            h.update(f.relative_to(path).as_posix().encode('utf-8'))
            with open(f, 'rb') as fh:
                for chunk in iter(lambda: fh.read(chunk_size), b''): h.update(chunk)
    else:
        with open(path, 'rb') as fh:
            for chunk in iter(lambda: fh.read(chunk_size), b''): h.update(chunk)
    return h.hexdigest()

# %% ../../nbs/04_data.external.ipynb 42
def _snapshot_id(url:str, hash:str) -> str: # Deterministic 12-char id from url+hash
    "Derive a stable snapshot id from `url` and content `hash`"
    return hashlib.sha256(f'{url}@{hash}'.encode('utf-8')).hexdigest()[:12]

# %% ../../nbs/04_data.external.ipynb 43
class DatasetSnapshot:
    "A record of a dataset's source url, local path, content hash, size and creation time"
    def __init__(self,
        url:str, # Source url the dataset was downloaded from
        path:str, # Local filesystem path to the extracted data
        hash:str, # Content hash of the extracted data (see `dataset_hash`)
        size:int, # Total size in bytes of the extracted data
        created:str=None, # ISO-8601 UTC creation timestamp (defaults to now)
        id:str=None # Snapshot id (defaults to a deterministic id from url+hash)
    ):
        self.url,self.path,self.hash,self.size = url,str(path),hash,size
        self.created = created or datetime.now(timezone.utc).isoformat()
        self.id = id or _snapshot_id(url, hash)

    def to_dict(self) -> dict:
        "Serialise the snapshot to a plain dict for JSON storage"
        return {'id':self.id, 'url':self.url, 'path':self.path, 'hash':self.hash,
                'size':self.size, 'created':self.created}

    @classmethod
    def from_dict(cls, d:dict) -> 'DatasetSnapshot':
        "Rebuild a `DatasetSnapshot` from its `to_dict` representation"
        return cls(url=d['url'], path=d['path'], hash=d['hash'], size=d['size'],
                   created=d.get('created'), id=d.get('id'))

    def __eq__(self, other):
        return isinstance(other, DatasetSnapshot) and self.to_dict()==other.to_dict()

    def __repr__(self):
        return f'DatasetSnapshot(id={self.id!r}, url={self.url!r}, path={self.path!r}, hash={self.hash!r}, size={self.size}, created={self.created!r})'

# %% ../../nbs/04_data.external.ipynb 44
def _read_lineage(
    path:Path=None # Lineage registry file (defaults to `fastai_lineage_path`)
) -> dict: # Mapping of snapshot id -> snapshot dict
    "Load the lineage registry, returning {} if it does not exist yet"
    path = Path(path) if path is not None else fastai_lineage_path()
    if not path.exists(): return {}
    try: return json.loads(path.read_text(encoding='utf-8'))
    except json.JSONDecodeError as e:
        raise ValueError(f'Corrupt lineage registry at {path}: {e}. Fix or remove the file to continue.') from e

# %% ../../nbs/04_data.external.ipynb 45
def _write_lineage(
    registry:dict, # Full id -> snapshot dict mapping to persist
    path:Path=None # Lineage registry file (defaults to `fastai_lineage_path`)
):
    "Atomically write the lineage `registry` to `path` (temp file then replace)"
    path = Path(path) if path is not None else fastai_lineage_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent/f'.{path.name}.{os.getpid()}.tmp'
    tmp.write_text(json.dumps(registry, indent=2, sort_keys=True), encoding='utf-8')
    os.replace(tmp, path)

# %% ../../nbs/04_data.external.ipynb 46
def register_snapshot(
    url:str, # Source url the dataset was downloaded from
    path:Path, # Local path to the extracted data to snapshot
    lineage_path:Path=None # Lineage registry file (defaults to `fastai_lineage_path`)
) -> DatasetSnapshot: # The registered (and persisted) snapshot
    "Hash the data at `path` and persist a `DatasetSnapshot` for `url` in the lineage registry"
    path = Path(path)
    hash = dataset_hash(path)
    size = sum(f.stat().st_size for f in path.rglob('*') if f.is_file()) if path.is_dir() else path.stat().st_size
    snap = DatasetSnapshot(url=url, path=path, hash=hash, size=size)
    registry = _read_lineage(lineage_path)
    prev = registry.get(snap.id)
    if prev is not None and prev.get('path') != snap.path:
        warnings.warn(f'Snapshot {snap.id!r} path changed from {prev["path"]!r} to {snap.path!r}; overwriting.')
    registry[snap.id] = snap.to_dict()
    _write_lineage(registry, lineage_path)
    return snap

# %% ../../nbs/04_data.external.ipynb 47
def list_snapshots(
    lineage_path:Path=None # Lineage registry file (defaults to `fastai_lineage_path`)
) -> list: # Snapshots sorted by creation time, newest first
    "Return all recorded `DatasetSnapshot`s, most recently created first"
    registry = _read_lineage(lineage_path)
    snaps = [DatasetSnapshot.from_dict(d) for d in registry.values()]
    return sorted(snaps, key=lambda s: (s.created, s.id), reverse=True)

# %% ../../nbs/04_data.external.ipynb 48
def get_snapshot(
    snapshot_id:str, # Id of the snapshot to fetch
    lineage_path:Path=None # Lineage registry file (defaults to `fastai_lineage_path`)
) -> DatasetSnapshot: # The matching snapshot
    "Fetch a `DatasetSnapshot` by id, raising `KeyError` if it is unknown"
    registry = _read_lineage(lineage_path)
    if snapshot_id not in registry:
        raise KeyError(f'Unknown snapshot id {snapshot_id!r}. Known ids: {sorted(registry)}')
    return DatasetSnapshot.from_dict(registry[snapshot_id])

# %% ../../nbs/04_data.external.ipynb 49
def reproduce_snapshot(
    snapshot_id:str, # Id of the snapshot to reproduce
    lineage_path:Path=None # Lineage registry file (defaults to `fastai_lineage_path`)
) -> Path: # Local path whose current contents match the recorded snapshot
    "Verify local data still matches the recorded snapshot and return its `Path` (no download)"
    snap = get_snapshot(snapshot_id, lineage_path)
    path = Path(snap.path)
    if not path.exists():
        raise FileNotFoundError(f'Snapshot {snapshot_id!r} references {path} which no longer exists; re-download {snap.url} to reproduce it.')
    current = dataset_hash(path)
    if current != snap.hash:
        raise ValueError(f'Local data at {path} no longer matches snapshot {snapshot_id!r} (hash {current} != {snap.hash}); re-download {snap.url} to reproduce it.')
    return path
