"""The function to immediately get a `Learner` ready to train for tabular data"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/43_tabular.learner.ipynb.

# %% ../../nbs/43_tabular.learner.ipynb 1
from __future__ import annotations
from ..basics import *
from .core import *
from .model import *
from .data import *

# %% auto 0
__all__ = ['TabularLearner', 'tabular_learner', 'show_results']

# %% ../../nbs/43_tabular.learner.ipynb 7
class TabularLearner(Learner):
    "`Learner` for tabular data"
    def predict(self, 
        row:pd.Series, # Features to be predicted
    ):
        "Predict on a single sample"
        dl = self.dls.test_dl(row.to_frame().T)
        dl.dataset.conts = dl.dataset.conts.astype(np.float32)
        inp,preds,_,dec_preds = self.get_preds(dl=dl, with_input=True, with_decoded=True)
        b = (*tuplify(inp),*tuplify(dec_preds))
        full_dec = self.dls.decode(b)
        return full_dec,dec_preds[0],preds[0]

    def fit_incremental(self,
        new_df:pd.DataFrame, # New data to incorporate (same schema as original training data)
        n_epoch:int=1, # Number of epochs to train on new data
        lr:float=None, # Learning rate; defaults to the learner's stored lr scaled down by 10x
        wd:float=None, # Weight decay; defaults to the learner's stored wd
        valid_pct:float=0.2, # Fraction of new data to use for validation
        bs:int=None, # Batch size; defaults to existing training DataLoader batch size
        cbs:list=None, # Additional callbacks for this incremental fit
        reset_opt:bool=False, # Whether to reset the optimizer (False preserves momentum/state)
    ):
        "Continue training on `new_df` without resetting model weights, enabling online/incremental learning"
        old_dls = self.dls
        try:
            # Reuse existing preprocessing config from the training dataset
            train_ds = old_dls.train_ds
            cat_names = list(train_ds.cat_names)
            cont_names = list(train_ds.cont_names)
            y_names = list(train_ds.y_names)
            procs = train_ds.procs

            # Build new Tabular dataset reusing fitted procs (no re-fitting)
            if bs is None: bs = old_dls.bs
            n_valid = max(1, int(len(new_df) * valid_pct))
            valid_idx = list(range(len(new_df) - n_valid, len(new_df)))
            splits = [list(range(len(new_df) - n_valid)), valid_idx]

            # Create new TabularPandas reusing existing fitted procs without re-setup
            new_to = TabularPandas(new_df, procs=procs, cat_names=cat_names, cont_names=cont_names,
                                   y_names=y_names, splits=splits, do_setup=False)
            new_to.process()
            new_dls = new_to.dataloaders(bs=bs)

            # Swap in the new DataLoaders and train
            self.dls = new_dls
            if lr is None: lr = self.lr / 10
            self.fit(n_epoch, lr=lr, wd=wd, cbs=cbs, reset_opt=reset_opt)
        finally:
            # Restore original DataLoaders so the learner remains usable for prediction
            self.dls = old_dls

# %% ../../nbs/43_tabular.learner.ipynb 10
@delegates(Learner.__init__)
def tabular_learner(
        dls:TabularDataLoaders,
        layers:list=None, # Size of the layers generated by `LinBnDrop`
        emb_szs:list=None, # Tuples of `n_unique, embedding_size` for all categorical features
        config:dict=None, # Config params for TabularModel from `tabular_config`
        n_out:int=None, # Final output size of the model
        y_range:Tuple=None, # Low and high for the final sigmoid function
        **kwargs
):
    "Get a `Learner` using `dls`, with `metrics`, including a `TabularModel` created using the remaining params."
    if config is None: config = tabular_config()
    if layers is None: layers = [200,100]
    to = dls.train_ds
    emb_szs = get_emb_sz(dls.train_ds, {} if emb_szs is None else emb_szs)
    if n_out is None: n_out = get_c(dls)
    assert n_out, "`n_out` is not defined, and could not be inferred from data, set `dls.c` or pass `n_out`"
    if y_range is None and 'y_range' in config: y_range = config.pop('y_range')
    model = TabularModel(emb_szs, len(dls.cont_names), n_out, layers, y_range=y_range, **config)
    return TabularLearner(dls, model, **kwargs)

# %% ../../nbs/43_tabular.learner.ipynb 19
@typedispatch
def show_results(x:Tabular, y:Tabular, samples, outs, ctxs=None, max_n=10, **kwargs):
    df = x.all_cols[:max_n]
    for n in x.y_names: df[n+'_pred'] = y[n][:max_n].values
    display_df(df)
